Use /jffs/addons/x3mRouting/x3mRouting_Menu.sh with link to /opt/bin/x3mRouting

diff --git a/x3mRouting b/x3mRouting
--- a/x3mRouting
+++ b/x3mRouting
@@ -2,7 +2,7 @@
 ####################################################################################################
 # Script: x3mRouting
 # Author: Xentrk
-# Last Updated Date: 2-April-2020
+# Last Updated Date: 3-May-2020
 #
 # Description:
 #  Install, Update or Remove the x3mRouting repository
@@ -17,7 +17,7 @@
 # shellcheck disable=SC2028
 export PATH=/sbin:/bin:/usr/sbin:/usr/bin$PATH
 logger -t "($(basename "$0"))" "$$ Starting Script Execution ($(if [ -n "$1" ]; then echo "$1"; else echo "menu"; fi))"
-VERSION="1.0.5"
+VERSION="1.1.0"
 GIT_REPO="x3mRouting"
 GITHUB_DIR="https://raw.githubusercontent.com/Xentrk/$GIT_REPO/master"
 LOCAL_REPO="/jffs/scripts/x3mRouting"
@@ -338,6 +338,20 @@ Remove_Existing_Installation() {
     else
       printf '\n%b"/opt/bin/x3mRouting"%b menu file removed\n' "$COLOR_GREEN" "$COLOR_WHITE"
     fi
+  fi
+
+  DIR="/jffs/addons/x3mRouting"
+  if [ -d "$DIR" ]; then
+	if ! rm -rf "${DIR:?}/"* 2>/dev/null; then
+		printf '\nNo files found to remove in %b%s%b\n' "$COLOR_GREEN" "$DIR" "$COLOR_WHITE"
+	fi
+	if ! rmdir "$DIR" 2>/dev/null; then
+		printf '\nError trying to remove %b%s%b\n' "$COLOR_GREEN" "$DIR" "$COLOR_WHITE"
+	else
+		printf '\n%b%s%b folder and all files removed\n' "$COLOR_GREEN" "$DIR" "$COLOR_WHITE"
+	fi
+  else
+      printf '\n%b%s%b folder does not exist. No directory to remove\n' "$COLOR_GREEN" "$DIR" "$COLOR_WHITE"
   fi
 
   Exit_Message
@@ -661,9 +675,16 @@ Update_Installer() {
     echo
     case "$menu_Update_Installer" in
     1)
-      Download_File /opt/bin x3mRouting
+      mkdir -p /jffs/addons/x3mRouting
+      Download_File /jffs/addons/x3mRouting x3mRouting_Menu.sh
+      chmod 755 /jffs/addons/x3mRouting/x3mRouting_Menu.sh
+      rm -rf "/opt/bin/x3mRouting" 2>/dev/null
+      if [ -d "/opt/bin" ] && [ ! -L "/opt/bin/x3mRouting" ]; then
+        echo "Creating 'x3mRouting' alias" 2>&1
+        ln -s /jffs/addons/x3mRouting/x3mRouting_Menu.sh /opt/bin/x3mRouting
+      fi
       printf '\nUpdate Complete! %s\n' "$remotemd5"
-      /opt/bin/x3mRouting
+      sh /jffs/addons/x3mRouting/x3mRouting_Menu.sh
       break
       ;;
     2)
