update x3mRouting menu for new version

diff --git a/x3mRouting b/x3mRouting
--- a/x3mRouting
+++ b/x3mRouting
@@ -2,7 +2,7 @@
 ####################################################################################################
 # Script: x3mRouting
 # Author: Xentrk
-# Last Updated Date: 2-April-2020
+# Last Updated Date: 13-April-2020
 #
 # Description:
 #  Install, Update or Remove the x3mRouting repository
@@ -17,7 +17,7 @@
 # shellcheck disable=SC2028
 export PATH=/sbin:/bin:/usr/sbin:/usr/bin$PATH
 logger -t "($(basename "$0"))" "$$ Starting Script Execution ($(if [ -n "$1" ]; then echo "$1"; else echo "menu"; fi))"
-VERSION="1.0.5"
+VERSION="2.0.0"
 GIT_REPO="x3mRouting"
 GITHUB_DIR="https://raw.githubusercontent.com/Xentrk/$GIT_REPO/master"
 LOCAL_REPO="/jffs/scripts/x3mRouting"
@@ -54,19 +54,19 @@ Welcome_Message() {
 
 Main_Menu() {
   printf '%b[1]%b  Install x3mRouting for LAN Clients\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
-  printf '%b[2]%b  Install x3mRouting OpenVPN Client GUI & IPSET Shell Scripts\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
-  printf '%b[3]%b  Install x3mRouting IPSET Shell Scripts\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
-  printf '%b[4]%b  Install route_all_vpnserver.sh\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
-  printf '%b[5]%b  Install route_ipset_vpnserver.sh\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
-  printf '%b[6]%b  Install x3mRouting OpenVPN Event\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
-  printf '      ** Install Option 6 if you have installed Method 1 + Method 3\n'
-  printf '%b[7]%b  Check for updates to existing x3mRouting installation\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
-  printf '%b[8]%b  Force update existing x3mRouting installation\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
-  printf '%b[9]%b  Remove x3mRouting Repository\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
+  printf '%b[2]%b  Install x3mRouting OpenVPN Client GUI, OpenVPN Event & Routing Script\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
+  printf '%b[3]%b  Install x3mRouting OpenVPN Event & Routing Script\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
+  printf '%b[4]%b  Install x3mRouting OpenVPN Event\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
+  printf '%b[5]%b  Check for updates to existing x3mRouting installation\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
+  printf '%b[6]%b  Force update existing x3mRouting installation\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
+  printf '%b[7]%b  Remove x3mRouting Repository\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
   localmd5="$(md5sum "/opt/bin/x3mRouting" | awk '{print $1}')"
   remotemd5="$(curl -fsL --retry 3 "${GITHUB_DIR}/x3mRouting" | md5sum | awk '{print $1}')"
   if [ "$localmd5" != "$remotemd5" ]; then
-    printf '%b[10]%b Update x3mRouting Menu\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
+    printf '%b[8]%b Update x3mRouting Menu\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
+  fi
+  if [ ! -f "LOCAL_REPO/x3mRouting.sh" ]; then
+    printf '%b[u]%b Update to new version of x3mRouting\n' "${COLOR_RED}" "${COLOR_WHITE}"
   fi
   printf '\n%b[e]%b  Exit Script\n' "${COLOR_GREEN}" "${COLOR_WHITE}"
   while true; do
@@ -80,38 +80,37 @@ Main_Menu() {
       ;;
     2)
       Install_x3mRouting_GUI
+      Install_x3mRouting_OpenVPN_Event
+      Install_x3mRouting_Shell_Scripts
       return 1
       ;;
     3)
+      Install_x3mRouting_OpenVPN_Event
       Install_x3mRouting_Shell_Scripts
       return 1
       ;;
     4)
-      Install_Route_All_VpnServer
-      return 1
-      ;;
-    5)
-      Install_Route_IPSET_Vpnserver
-      return 1
-      ;;
-    6)
       Install_x3mRouting_OpenVPN_Event
       return 1
       ;;
-    7)
+    5)
       Confirm_Update
       return 1
       ;;
-    8)
+    6)
       Confirm_Update force
       return 1
       ;;
-    9)
+    7)
       Validate_Removal
       return 1
       ;;
-    10)
+    8)
       Update_Installer
+      return 1
+      ;;
+    u)
+      Update_NewVersion
       return 1
       ;;
     e)
@@ -213,21 +212,12 @@ Update_Version() {
     for FILE in vpnrouting.sh \
       updown-client.sh \
       Advanced_OpenVPNClient_Content.asp \
+      x3mRouting.sh \
       x3mRouting_client_nvram.sh \
       x3mRouting_client_config.sh \
       mount_files_lan.sh \
       mount_files_gui.sh \
-      load_MANUAL_ipset.sh \
-      load_ASN_ipset.sh \
-      load_DNSMASQ_ipset.sh \
-      load_AMAZON_ipset.sh \
-      load_MANUAL_ipset_iface.sh \
-      load_ASN_ipset_iface.sh \
-      load_DNSMASQ_ipset_iface.sh \
-      load_AMAZON_ipset_iface.sh \
-      openvpn-event \
-      route_all_vpnserver.sh \
-      route_ipset_vpnserver.sh;do
+      openvpn-event;do
       if [ -s "$DIR/$FILE" ]; then
         if [ -z "$1" ]; then
           if [ "$FILE" != "openvpn-event" ]; then
@@ -279,6 +269,356 @@ Update_Version() {
   read -r
   Welcome_Message
 }
+
+Update_NewVersion() {
+  # This script will clean-up old files and create a conversion file
+
+  PROJECT_REPO=/jffs/scripts/x3mRouting
+  NAT_START=/jffs/scripts/nat-start-bkup
+  CONV_FILE=/jffs/scripts/x3mRouting/x3mRouting_Conversion.sh
+
+  # Only Backup the Old Project Repo Directory during the first run to prevent potential corruption
+  if [ -d "$PROJECT_REPO" ]; then
+    if [ ! -d "$PROJECT_REPO/backup" ]; then
+      mkdir "$PROJECT_REPO/backup"
+      cp -a "$PROJECT_REPO/." "$PROJECT_REPO/backup/ >/dev/null 2>&1"
+    else
+      echo "Existing backup directory found. Skipping backup step."
+    fi
+  fi
+
+  true > "$CONV_FILE" && chmod 755 "$CONV_FILE"
+
+  Conversion_Msg() {
+    {
+      echo "# Source File====> $FILE"
+      echo "# Original Entry=> $LINE"
+      echo "$LINE4"
+      echo ""
+    } >> "$CONV_FILE"
+  }
+
+  Warning_Msg() {
+    {
+      echo "# If the source VPN Client you want to bypass is '1', then no changes are required."
+      echo "# Otherwise, edit the '1' to be a valid VPN Client number '1-5'"
+    }>> "$CONV_FILE"
+  }
+
+  Process_File() {
+
+    FILE=$1
+
+    if [ "$(grep -c x3mRouting "$FILE")" -gt 0 ]; then
+      grep x3mRouting "$FILE" | while read -r LINE; do
+
+      # Skip comment lines
+        LINETYPE=$(echo "$LINE" | awk  '{ string=substr($0, 1, 1); print string;}')
+        if [ "$LINETYPE" = "#" ]; then
+          continue
+        fi
+
+      # AMAZON
+        if [ "$(echo "$LINE" | grep  -c load_AMAZON_ipset_iface.sh)" -ge 1 ]; then
+          LINE2=$(echo "$LINE" | sed 's/load_AMAZON_ipset_iface.sh/x3mRouting.sh/' | sed 's/ 1/ ALL 1/' | sed 's/ 2/ ALL 2/' | sed 's/ 3/ ALL 3/' | sed 's/ 4/ ALL 4/'| sed 's/ 5/ ALL 5/' | sed 's/ 0/ 1 0/')
+          AWS_REGION=$(echo "$LINE2" | awk '{ print substr( $0, length($0) - 1, length($0) ) }')
+          LINE3=$(echo "$LINE2" | awk '{print $1, $2, $3, $4, $5}')
+          LINE4="$LINE3 aws_region=$AWS_REGION"
+          if [ "$(echo "$LINE4" | grep  -c "1 0")" -ge 1 ]; then
+            Warning_Msg
+          fi
+          Conversion_Msg
+          continue
+        fi
+
+        if [ "$(echo "$LINE" | grep  -c load_AMAZON_ipset.sh)" -ge 1 ]; then
+          LINE2=$(echo "$LINE" | sed 's/load_AMAZON_ipset.sh/x3mRouting.sh/')
+          IPSET=$(echo "$LINE2" | awk '{print $3}' )
+          AWS_REGION=$(echo "$LINE2" | awk '{ print substr( $0, length($0) - 1, length($0) ) }')
+          LINE3=$(echo "$LINE2" | awk '{print $1, $2}')
+          LINE4="$LINE3 ipset_name=$IPSET aws_region=$AWS_REGION"
+          Conversion_Msg
+          continue
+        fi
+
+        # ASN
+        if [ "$(echo "$LINE" | grep  -c load_ASN_ipset_iface.sh)" -ge 1 ]; then
+          LINE2=$(echo "$LINE" | sed 's/load_ASN_ipset_iface.sh/x3mRouting.sh/' | sed 's/ 1/ ALL 1/' | sed 's/ 2/ ALL 2/' | sed 's/ 3/ ALL 3/' | sed 's/ 4/ ALL 4/'| sed 's/ 5/ ALL 5/' | sed 's/ 0/ 1 0/')
+          ASNUM=$(echo "$LINE2" | sed -ne 's/^.*AS//p')
+          ASN="AS${ASNUM}"
+          LINE3=$(echo "$LINE2" | awk '{print $1, $2, $3, $4, $5}')
+          LINE4="$LINE3 asnum=$ASN"
+          if [ "$(echo "$LINE4" | grep  -c "1 0")" -ge 1 ]; then
+            Warning_Msg
+          fi
+          Conversion_Msg
+          continue
+        fi
+        if [ "$(echo "$LINE" | grep  -c load_ASN_ipset.sh)" -ge 1 ]; then
+          LINE2=$(echo "$LINE" | sed 's/load_ASN_ipset.sh/x3mRouting.sh/')
+          IPSET=$(echo "$LINE2" | awk '{print $3}')
+          ASNUM=$(echo "$LINE2" | sed -ne 's/^.*AS//p')
+          ASN="AS${ASNUM}"
+          LINE3=$(echo "$LINE2" | awk '{print $1, $2}')
+          LINE4="$LINE3 ipset_name=$IPSET asnum=$ASN"
+          Conversion_Msg
+          continue
+        fi
+
+        # DNSMASQ
+        if [ "$(echo "$LINE" | grep  -c load_DNSMASQ_ipset_iface.sh)" -ge 1 ]; then
+          LINE2=$(echo "$LINE" | sed 's/load_DNSMASQ_ipset_iface.sh/x3mRouting.sh/' | sed 's/ 1/ ALL 1/' | sed 's/ 2/ ALL 2/' | sed 's/ 3/ ALL 3/' | sed 's/ 4/ ALL 4/'| sed 's/ 5/ ALL 5/' | sed 's/ 0/ 1 0/')
+          IPSET=$(echo "$LINE2" | awk '{print $5}' )
+          DNSMASQ=$(echo "$LINE2" | awk '{print $6}' )
+          LINE3=$(echo "$LINE2" | awk '{print $1, $2, $3, $4, $5}')
+          LINE4="$LINE3 dnsmasq=$DNSMASQ"
+          if [ "$(echo "$LINE4" | grep  -c "1 0")" -ge 1 ]; then
+            Warning_Msg
+          fi
+          Conversion_Msg
+          continue
+        fi
+        if [ "$(echo "$LINE" | grep  -c load_DNSMASQ_ipset.sh)" -ge 1 ]; then
+          LINE2=$(echo "$LINE" | sed 's/load_DNSMASQ_ipset.sh/x3mRouting.sh/')
+          IPSET=$(echo "$LINE2" | awk '{print $3}' )
+          DNSMASQ=$(echo "$LINE2" | awk '{print $4}' )
+          LINE3=$(echo "$LINE2" | awk '{print $1, $2}')
+          LINE4="$LINE3 ipset_name=$IPSET dnsmasq=$DNSMASQ"
+          Conversion_Msg
+          continue
+        fi
+
+        # MANUAL
+        if [ "$(echo "$LINE" | grep  -c load_MANUAL_ipset_iface.sh)" -ge 1 ]; then
+          LINE2=$(echo "$LINE" | sed 's/load_MANUAL_ipset_iface.sh/x3mRouting.sh/' | sed 's/ 1/ ALL 1/' | sed 's/ 2/ ALL 2/' | sed 's/ 3/ ALL 3/' | sed 's/ 4/ ALL 4/'| sed 's/ 5/ ALL 5/' | sed 's/ 0/ 1 0/')
+          LINE3=$(echo "$LINE2" | awk '{print $1, $2, $3, $4, $5}')
+          LINE4="$LINE3"
+          if [ "$(echo "$LINE4" | grep  -c "1 0")" -ge 1 ]; then
+            Warning_Msg
+          fi
+          Conversion_Msg
+          continue
+        fi
+        if [ "$(echo "$LINE" | grep  -c load_MANUAL_ipset.sh)" -ge 1 ]; then
+          LINE2=$(echo "$LINE" | sed 's/load_MANUAL_ipset.sh/x3mRouting.sh/')
+          IPSET=$(echo "$LINE2" | awk '{print $3}')
+          LINE3=$(echo "$LINE2" | awk '{print $1, $2}')
+          LINE4="$LINE3 ipset_name=$IPSET"
+          Conversion_Msg
+          continue
+        fi
+
+      done
+    fi
+
+}
+
+Check_For_Shebang() {
+
+  CLIENTX_FILE=$1
+  SHEBANG_COUNT=0
+  EMPTY_LINE_COUNT=0
+  NOT_EMPTY_LINE_COUNT=0
+  COMMENT_LINE_COUNT=0
+
+  if [ -f "$CLIENTX_FILE" ]; then # file exists
+    while read -r LINE || [ -n "$LINE" ]
+    do
+      if [ "$LINE" = "#!/bin/sh" ]; then
+        SHEBANG_COUNT=$((SHEBANG_COUNT + 1))
+        continue
+      fi
+
+      linetype=$(echo "$LINE" | awk '{ string=substr($0, 1, 1); print string; }')
+      if [ "$linetype" = "#" ]; then
+        COMMENT_LINE_COUNT=$((COMMENT_LINE_COUNT + 1))
+        continue
+      fi
+
+      if [ -z "$LINE" ]; then
+	      EMPTY_LINE_COUNT=$((EMPTY_LINE_COUNT + 1))
+        continue
+      fi
+
+      if [ -n "$LINE" ]; then
+	      NOT_EMPTY_LINE_COUNT=$((NOT_EMPTY_LINE_COUNT + 1))
+        continue
+      fi
+    done < "$CLIENTX_FILE"
+  else
+    return
+  fi
+
+  if [ "$NOT_EMPTY_LINE_COUNT" -eq 0 ]; then
+    printf '\n\n%s\n' "$CLIENTX_FILE has $SHEBANG_COUNT shebang entry, $NOT_EMPTY_LINE_COUNT valid lines, $COMMENT_LINE_COUNT comment lines and $EMPTY_LINE_COUNT empty lines."
+    printf '%s\n' "Would you like to remove $TESTMYFILE?"
+    printf '[1]  --> Yes\n'
+    printf '[2]  --> No\n'
+    echo
+    while true; do
+      printf '[1-2]: '
+      read -r "OPTION"
+      case "$OPTION" in
+      1)
+        rm "$CLIENTX_FILE"
+        echo "$CLIENTX_FILE file deleted"
+        return
+        ;;
+      2)
+        return
+        ;;
+      *)
+        echo "[*] $OPTION Isn't An Option!"
+        ;;
+      esac
+    done
+  else
+    printf '\n\n%s\n' "$CLIENTX_FILE has $SHEBANG_COUNT shebang entry, $NOT_EMPTY_LINE_COUNT valid lines, $COMMENT_LINE_COUNT comment lines and $EMPTY_LINE_COUNT empty lines."
+    printf '%s\n' "Skipping removal of $CLIENTX_FILE."
+  fi
+
+}
+
+# Remove old version entries from nat-start
+Remove_From_nat_start() {
+
+  if [ -s "$NAT_START" ]; then
+    TIMESTAMP=$(date +"%Y-%m-%d-%H.%M.%S")
+    if ! cp "$NAT_START" "$NAT_START"."$TIMESTAMP"; then
+      printf '\nBackup of the prior %s file could not be made.\n' "$NAT_START"
+      printf 'Exiting...\n'
+      return
+    else
+      printf '\nExisting %s file found.\n' "$NAT_START"
+      printf 'Backup file saved to %s.\n' "$NAT_START.$TIMESTAMP"
+    fi
+
+    for OLD_FILE in load_MANUAL_ipset.sh load_ASN_ipset.sh load_DNSMASQ_ipset.sh load_AMAZON_ipset.sh load_MANUAL_ipset_iface.sh load_ASN_ipset_iface.sh load_DNSMASQ_ipset_iface.sh load_AMAZON_ipset_iface.sh route_all_vpnserver.sh route_ipset_vpnserver.sh; do
+      if [ "$(grep -c "$OLD_FILE" "$NAT_START")" -ge "1" ]; then # if true, then lines exist
+        sed -i "/$OLD_FILE/d" "$NAT_START" && echo "Deleted $OLD_FILE entry from $NAT_START"
+        Check_For_Shebang "$NAT_START"
+      fi
+    done
+  fi
+
+}
+
+# Remove old version entries from vpnclienX-route-up file
+Remove_From_UP_File() {
+
+  for VPNID in 1 2 3 4 5; do
+    UP_FILE=/jffs/scripts/x3mRouting/vpnclient${VPNID}-route-up
+    if [ -s "$UP_FILE" ]; then # file exists
+      for OLD_FILE in load_MANUAL_ipset.sh load_ASN_ipset.sh load_DNSMASQ_ipset.sh load_AMAZON_ipset.sh load_MANUAL_ipset_iface.sh load_ASN_ipset_iface.sh load_DNSMASQ_ipset_iface.sh load_AMAZON_ipset_iface.sh route_all_vpnserver.sh route_ipset_vpnserver.sh; do
+        if [ "$(grep -c "$OLD_FILE" "$UP_FILE")" -ge "1" ]; then # if true, then lines exist
+          sed -i "/$OLD_FILE/d" "$UP_FILE"
+          Check_For_Shebang "$UP_FILE"
+        fi
+      done
+    fi
+  done
+
+}
+
+Remove_Old_Files() {
+
+  for OLD_FILE in load_MANUAL_ipset.sh load_ASN_ipset.sh load_DNSMASQ_ipset.sh load_AMAZON_ipset.sh load_MANUAL_ipset_iface.sh load_ASN_ipset_iface.sh load_DNSMASQ_ipset_iface.sh load_AMAZON_ipset_iface.sh route_all_vpnserver.sh route_ipset_vpnserver.sh; do
+    [ -f "$PROJECT_REPO/$OLD_FILE" ] && rm "$PROJECT_REPO/$OLD_FILE" echo "Obsolete $PROJECT_REPO/$OLD_FILE file deleted" || echo "Obsolete $PROJECT_REPO/$OLD_FILE file does not exist"
+  done
+
+}
+
+## End of Functions
+
+## ============================== Begin
+
+# If a previous version of the conversion file exists, back it up to prevent overwrite as a second run may corrupt it
+if [ -f "$PROJECT_REPO/x3mRouting_Conversion.sh" ]; then
+  TIMESTAMP=$(date +"%Y-%m-%d-%H.%M.%S")
+  if ! cp "$PROJECT_REPO/x3mRouting_Conversion.sh" "$PROJECT_REPO/x3mRouting_Conversion.sh.$TIMESTAMP"; then
+    printf '\nBackup of the prior %s file could not be made.\n' "$PROJECT_REPO/x3mRouting_Conversion.sh"
+    printf 'Exiting...\n'
+    exit 0
+  else
+    printf '\nExisting %s file found.\n' "$PROJECT_REPO/x3mRouting_Conversion.sh"
+    printf 'Backup file saved to %s.\n' "$PROJECT_REPO/x3mRouting_Conversion.sh.$TIMESTAMP"
+  fi
+fi
+
+# Process any vpnclientX-route-up files in x3mRouting directory
+for VPNID in 1 2 3 4 5; do
+  UP_FILE=/jffs/scripts/x3mRouting/vpnclient${VPNID}-route-up
+  if [ -s "$UP_FILE" ]; then # file exists
+    Process_File "$UP_FILE"
+  fi
+done
+
+# Process nat-start
+if [ -f "$NAT_START" ]; then
+  Process_File "$NAT_START"
+fi
+
+# add shebang to the first line before exiting
+if [ -s "$CONV_FILE" ]; then
+  sed -i '1s/^/#!\/bin\/sh\/\n/' "$CONV_FILE"
+  echo "Created $CONV_FILE script to assist with the conversion."
+  echo "Please review the script before running"
+else
+  echo "$CONV_FILE script not created. No valid x3mRouting entries found in $NAT_START or vpnclientX-route-up files."
+  rm "$CONV_FILE"
+fi
+
+# Give user the option to remove the prior verson of any x3mRouting entries found in $NAT_START or vpnclientX-route-up files"
+
+printf '%s\n' "Would you like to check for and remove obsolete x3mRouting files from $PROJECT_REPO?"
+printf '%s\n' "The recommondation is to select option 1 in order to maintain a clean project repository."
+printf '%s\n\n' "x3mRouting backup files are stored in the $PROJECT_REPO/backup directory for easy recovery."
+printf '[1]  --> Yes\n'
+printf '[2]  --> No\n'
+echo
+while true; do
+  printf '[1-2]: '
+  read -r "OPTION"
+  case "$OPTION" in
+  1)
+    Remove_Old_Files
+    break
+    ;;
+  2)
+    break
+    ;;
+  *)
+    echo "[*] $OPTION Isn't An Option!"
+    ;;
+    esac
+done
+
+printf '%s\n' "Would you like to check for and remove prior x3mRouting version entries found in $NAT_START or vpnclientX-route-up files?"
+printf '%s\n' "The recommondation is to select option 1 in order to remove prior x3mRouting version entries."
+printf '%s\n\n' "Backup files are stored in the $PROJECT_REPO/backup directory for easy recovery."
+printf '[1]  --> Yes\n'
+printf '[2]  --> No\n'
+echo
+while true; do
+  printf '[1-2]: '
+  read -r "OPTION"
+  case "$OPTION" in
+  1)
+    Remove_From_nat_start
+    Remove_From_UP_File
+    break
+    ;;
+  2)
+    break
+    ;;
+  *)
+    echo "[*] $OPTION Isn't An Option!"
+    ;;
+    esac
+done
+
+}
+
 
 Remove_Existing_Installation() {
   echo "Starting removal of x3mRouting Repository"
@@ -573,16 +913,13 @@ Install_x3mRouting_GUI() {
   Download_File "$LOCAL_REPO" "vpnrouting.sh"
   Download_File "$LOCAL_REPO" "updown-client.sh"
   Download_File "$LOCAL_REPO" "Advanced_OpenVPNClient_Content.asp"
-  Download_File "$LOCAL_REPO" "load_MANUAL_ipset.sh"
-  Download_File "$LOCAL_REPO" "load_ASN_ipset.sh"
-  Download_File "$LOCAL_REPO" "load_DNSMASQ_ipset.sh"
-  Download_File "$LOCAL_REPO" "load_AMAZON_ipset.sh"
+  Download_File "$LOCAL_REPO" "x3mRouting.sh"
   Download_File "$LOCAL_REPO" "mount_files_gui.sh"
   Init_Start_Update "mount_files_gui.sh"
   sh /jffs/scripts/init-start
   Check_Profile_Add
   echo
-  echo "Installation of x3mRouting for IPSET lists completed"
+  echo "Installation of x3mRouting completed"
   echo "Press enter to continue"
   read -r
   Welcome_Message
@@ -592,37 +929,10 @@ Install_x3mRouting_Shell_Scripts() {
 
   Check_Requirements
   Create_Project_Directory
-  Download_File "$LOCAL_REPO" "load_MANUAL_ipset_iface.sh"
-  Download_File "$LOCAL_REPO" "load_ASN_ipset_iface.sh"
-  Download_File "$LOCAL_REPO" "load_DNSMASQ_ipset_iface.sh"
-  Download_File "$LOCAL_REPO" "load_AMAZON_ipset_iface.sh"
+  Download_File "$LOCAL_REPO" "x3mRouting.sh"
   Check_Profile_Add
   echo
-  echo "Installation of x3mRouting for IPSET Shell Scripts completed"
-  echo "Press enter to continue"
-  read -r
-  Welcome_Message
-
-}
-
-Install_Route_All_VpnServer() {
-
-  Create_Project_Directory
-  Download_File "$LOCAL_REPO" "route_all_vpnserver.sh"
-  Check_OpenVPN_Event
-  echo
-  echo "Press enter to continue"
-  read -r
-  Welcome_Message
-
-}
-
-Install_Route_IPSET_Vpnserver() {
-
-  Create_Project_Directory
-  Download_File "$LOCAL_REPO" "route_ipset_vpnserver.sh"
-  Check_OpenVPN_Event
-  echo
+  echo "Installation of x3mRouting completed"
   echo "Press enter to continue"
   read -r
   Welcome_Message
